### ISSUE TITLE
Usage for different languages

### ISSUE THREAD

**Issue by tigerninjaman** [stanfordnlp/python-stanford-corenlp#22]
I am attempting to use this package for Chinese language segmenting and tagging. As #11 is 6 months old with no responses, I decided to open another issue.
I have downloaded stanford-chinese-corenlp-2018-02-27-model.jar, and I have the segmenter working for English. I am not sure how to specify a model .jar to use, and I cannot find a tutorial anywhere online. Some help and/or more in-depth walkthrough of how to use the segmenter would be much appreciated.

**Comment by GrazingScientist** [comment]
I also struggle with this issue. My solution was to run my own Stanford-Server.
It's really simple. Just follow the instructions given in this issue from a sister project: https://github.com/nltk/nltk/wiki/Stanford-CoreNLP-API-in-NLTK
There is even a detailled description for setting up a Chinese server model (but you have to first get some of the downloads from the top of the page):
https://github.com/nltk/nltk/wiki/Stanford-CoreNLP-API-in-NLTK#chinese

When the server is running, you can apply (in my case for german) (the endpoint is of course your server address with the correct port):

```
text= "Donald Trump besuchte Angela Merkel in Berlin."

with corenlp.CoreNLPClient(start_server=False, endpoint='http://localhost:9002') as client:
    ann = client.annotate(text)

sentence = ann.sentence[0]
print(sentence)
```

Oh! And don't bother because of the really, really, really slow start-up phase of the server and the first query. In this moment everything has to be loaded. The second query then is fast as hell. :)

**Comment by arunchaganty** [comment]
@tigerninjaman: I've provided some additional guidance for how to setup CoreNLP for other languages in #11. Once again, https://stanfordnlp.github.io/CoreNLP/human-languages.html will point you to the right properties files to use for this purpose. Don't forget to download the appropriate models for your language from https://stanfordnlp.github.io/CoreNLP/index.html#download.
